### PR TITLE
1 set up project

### LINKED ISSUE #1: Set up project

### PR DESCRIPTION
**Pull request by OleAndreasER**
Generated template Kotlin project with Android Studio.
There is a file, "local.properties", that is ignored by git since it should be different for each machine. If nothing works, that might be what's missing for you. Surely it gets generated by Android Studio.
I set up a github issue with a branch. Let's just use the generated branch names (1-set-up-project).
Commit message conventions I followed:
- lower case
- imperative verb  

I'm not a fan of type and scope ("feat(api): ..."), but we can use it if you want to, along with other conventions.

I configured Ktlint, a linter. Rules are in ".editorconfig".
With how I set it up in "build.gradle.kts", two commands are available (on Windows, at least):
- "./gradlew ktlintCheck"
- "./gradlew ktlintFormat"

However, everyone should install the Ktlint plugin in Android Studio, and configure it to autoformat on save. I think this plugin should suffice to enforce code style, but we could also add a pre-commit hook.

### CODE REVIEW

**Comment by michaelbrusegard** [comment]
Nice work, I will check if I can get it working myself before accepting the PR. For commit message formatting we can discuss that in the group, but I am not opposed to anything. The same goes for linting and formatting rules (but I prefer single quotes). I was also wondering why we need so many seperate .gitignore files and can't just have a single one.

**Comment by michaelbrusegard** [comment]
I forgot to mention. Before merging we should add a README.md with how to setup the dev environment as well as what type of standards we are using for commit messages, variable names (camelCase, snakeCase, etc.). And also links to documentation. That can be very useful

**Comment by OleAndreasER** [comment]
In Java and Kotlin, single quotes are for characters and double quotes for strings. The gitignores were generated. I'll remove them. Should add a setup guide and commit standards in the readme in this branch, yes. The others, not yet.

**Comment by michaelbrusegard** [comment]
I don't want this to be merged until we get the lint GitHub action working and/or setting up pre-commit hooks. I don't have experience with pre-commit hooks for Kotlin and Gradle sicne I have only used husky with node. I think we can figure something out. Will try to learn before Thursday :)

**Comment by michaelbrusegard** [comment]
Also we should fix a README.md that explains which emulators we use, how we can build the project, setup the dev environment etc.

**Comment by michaelbrusegard** [comment]
It would be nice if someone with more experience in Android Studio could improve the install instructions. The vscode solution is very complex so I don't think it will be used much by any else than me.

Also I was thinking maybe we should add some sort of i18n plugin to seperate our text from the code, and access it using keys. We could probably use a simple json file but I think there are plugins for this. This would also be good if we end up having to add more locales. We should also do some research on dark mode because it is a lot easier to set these things up before we have coded a lot.

**Comment by OleAndreasER** [comment]
I think you're cluttering the README with that vscode guide. Isn't there a guide on another website you could link to? Or link to another document? Not sure what's wrong with the Android Studio installation section. I don't see why there should be a detailed guide in our readme when there's a website. As for which emulator to use, surely they all work. I just picked a random one. I don't know what i18n is. They told us we didn't need dark mode. Good job on the rest. You want us to use "chore: " etc.? I'm ok with that. Add it to conventions in readme?

**Comment by michaelbrusegard** [comment]
- I didn’t notice my commits had the conventional syntax. I am using an extension so it happens automatically, but I can add that to the readme if you want. 
- There aren’t any articles that show how to develop for android in vscode, I wrote it because you had a section for android studio so I added for vscode in case anybody wanted that except me. You can delete it or move it if you want to. 
- i18n means internationalisation and it is used when you want to support multiple languages, in this case I want to use it to avoid hardcoding text because it is generally a bad practice. Instead the places you have text you use keys to access it. For example a key like menuDescription links to a string with a description for a menu. 
- I know they told us we don’t need dark mode, but we should still have color variables and not hard code the colors, this way it can be easily changed in one place if we wanted to add dark mode in the future or change the color. 
What do you think

**Review by michaelbrusegard — APPROVED** [review]

**Pull request merged**
