### PR TITLE
add interstitial ad after returning from emoji details

### PR DESCRIPTION
**Pull request by OleAndreasER**
Interstitial ads are fullscreen ads. I added one that is displayed when returning from emoji details - only if it finished loading by then. I didn't test because the test would take a lot of time to run and it would require internet connection. There's a singleton that we can use to disable ads for testing.

### CODE REVIEW

**Comment by YounesBB** [comment]
Works fine when using a Pixel_3a_API_34_extension_level_7_x86_64 emulator , but not when using pixel Pixel 6a API UpsideDownCakePrivacySandbox. This is something that should be looked into.

**Comment by OleAndreasER** [comment]
I can't get the UpsideDownCakePrivacySandbox emulator to run on my machine. I will fix merge conflicts once #91 is merged in dev. Not sure if I'll be able to fix the privacy sandbox thing. Can't find any information about it anywhere.

**Comment by YounesBB** [comment]
Alright, looks fine now.

**Review by YounesBB — APPROVED** [review]
Looks good. Let's merge it then!

**Pull request merged**
