### PR TITLE
add a search UI for all searched emojis

### LINKED ISSUE #41: Add a search UI for all searched emojis
Add a new grid view for all emojis searched

### PR DESCRIPTION
**Pull request by Andreasli02**
Now renders new EmojiGrid if user has searched. Filter logic is moved to SearchScreen from EmojiCatalogueUi. Not sure if there is a better way for conditional rendering. 

closes #41

### CODE REVIEW

**Review by OleAndreasER — CHANGES_REQUESTED** [review]
The emoji grid that appears has different styling than normal categories. If you're going to have a header ("Search results for:"), why not just use the catalogue ui with that as the sole category? It's good that you moved the search filtering outside of catalogue ui; but I would put the search logic inside EmojiCatalogue. Then you can more easily filter by search query on a list of emojis internally. If you look at the top comment in EmojiCatalogue, you'll see that was the original intention.

**Comment by Andreasli02** [comment]
> The emoji grid that appears has different styling than normal categories. If you're going to have a header ("Search results for:"), why not just use the catalogue ui with that as the sole category? It's good that you moved the search filtering outside of catalogue ui; but I would put the search logic inside EmojiCatalogue. Then you can more easily filter by search query on a list of emojis internally. If you look at the top comment in EmojiCatalogue, you'll see that was the original intention.

Moved search logic to EmojiCatalogue. Fixed styling to match normal categories. Also fixed tests that were broken. 

Tought the point of this issue was making new EmojiGrid for searched emojis. Not sure how I would use catalogue ui like you mentioned.

**Comment by OleAndreasER** [comment]
This is how you would do it. It seems good how you did it too.  
image

You should think about the performance of the search method you made. It gets called often, and each time it has to translate byCategory into a list of all emojis, before filtering.  Does it need to?

More importantly, the search method should be tested. Don't be scared of merge conflicts with the other branch that tests EmojiCatalogue. But look at it to make sure it's the same file in the same location.

**Comment by OleAndreasER** [comment]
No sorry there is another issue for testing search functionality.

**Review by OleAndreasER — APPROVED** [review]

**Pull request merged**
