### PR TITLE
5 grid layout with categories for emojis

### LINKED ISSUE #5: Grid layout with categories for emojis
Create a grid layout looking like the photo below including categories. It should be scrollable and responsive for different phone sizes.
Screenshot 2024-02-06 at 12 53 17

### LINKED ISSUE #23: Catalog for search page
Create a catalog view for search page. Should show a view over categorygrids where emojis and their category name is showcased.

### PR DESCRIPTION
**Pull request by OleAndreasER**
Take a look at the styling, see if you have improvements.  
Is "EmojiCatalogueUi" a good name to differentiate it with the data type it uses, "EmojiCatalogue"?  
I commented out the routing on emoji icons so it doesn't crash when you press them.  
The category scrollbar looks off, but you can take care of that when you merge with this.  

Closes #5

### CODE REVIEW

**Review by michaelbrusegard — APPROVED** [review]
looks great, I think the styling is done very well

**Comment by michaelbrusegard** [comment]
I think maybe we should make the emojis smaller and have more per category, what do you think?

**Comment by OleAndreasER** [comment]
image
This is displaySmall. I think maybe only the All tab should have a limit on the number of emojis.

**Comment by michaelbrusegard** [comment]
Screenshot 2024-02-21 at 12 21 50
Screenshot 2024-02-21 at 12 22 30

**Comment by OleAndreasER** [comment]
Ok but don't commit in my branch yo

**Comment by michaelbrusegard** [comment]
what do you think of that change, we can revert the commit if it is worse. I also set the padding to 4 instead of 5 which makes it more friendly to different screen sizes when i chooses to overlap to a new line. Do you know if we can dynamically set the limit of emojis per grid to be the amount er a single line times 3 for example?

**Comment by michaelbrusegard** [comment]
> Ok but don't commit in my branch yo

you said in review text that I should take a look at the styling, I thought that meant to open it and try to improve. I can revert the commit if you want

**Comment by OleAndreasER** [comment]
It's better, I think. Surely that is possible. I'll figure it out.

**Comment by michaelbrusegard** [comment]
I think this will have merge conflicts with #31 based on which of the branches we merge first

**Comment by OleAndreasER** [comment]
Scared? Merge this first, then merge/rebase this into #31 so we can see if it looks good with the catalogue.

**Comment by OleAndreasER** [comment]
I have been looking into it, and it seems possible but complicated and ugly. It's not worth doing yet in my opinion. Should we merge and then I test in another issue or in this one?

**Review by michaelbrusegard — APPROVED** [review]
I think all conflicts has been fixed after the rebase, still need to fix the dynamic amount of emojis per grid if we dont want to move that to its own issue

**Comment by OleAndreasER** [comment]
Definitely move it to another issue. It's not easy to implement and not so important right now.

**Pull request merged**
