### PR TITLE
57 add header logo 1

### PR DESCRIPTION
**Pull request by OleAndreasER**
Original: #61 

I did not put it in topBar in scaffold. It did not look good with animations, and not all screens should have the logo.

### CODE REVIEW

**Comment by michaelbrusegard** [comment]
@OleAndreasER screenshot

**Comment by OleAndreasER** [comment]
@michaelbrusegard Is it just me or do you get this as well? I think it might be painter resource.  
image

**Comment by OleAndreasER** [comment]
I think it's just me.

**Comment by OleAndreasER** [comment]
image

**Comment by michaelbrusegard** [comment]
> @michaelbrusegard Is it just me or do you get this as well? I think it might be painter resource. image

I dont get that error, except when my laptop is very hot

**Comment by michaelbrusegard** [comment]
lgtm!

**Pull request merged**
